---
- name: launch instances
  ec2:
    key_name: '{{ keypair }}'
    group: default
    instance_type: '{{ instance_type }}'
    image: '{{ image }}'
    wait: yes
    wait_timeout: 500
    region: '{{ region }}'
    assign_public_ip: true
    vpc_subnet_id: "subnet-7b960255"
    exact_count: 1
    count_tag:
      Name: "{{ item.hostname }}"
    instance_tags:
      Name: "{{ item.hostname }}"
    instance_profile_name: set-internal-dns
    user_data: "{{ lookup('template', 'templates/user_data_route53_dns.yml.j2') }}"
  with_items:
    - hostname: "{{ ec2_hostname }}"
      fqdn: "{{ ec2_hostname }}.{{ domain }}"
  register: ec2
- name: print all variables
  debug: var=ec2
