---
- name: Clone code repository
  git:
    repo: https://github.com/puppettst3/sample-html.git
    dest: /usr/local/apache2/sample-html

- name: Install apache webserver inside the container
  docker_service:
    project_name: webserver
    definition:
      version: '2'
      services:
        webserver:
          image: httpd
          volumes:
            - "/usr/local/apache2/sample-html:/usr/local/apache2/htdocs/"
          ports:
            - "80:80"
