---
dependencies: []

galaxy_info:
  author: Kishore Kumar
  description: Pip (Python package manager) for Linux.
  issue_tracker_url: https://github.com/geerlingguy/ansible-role-pip/issues
  min_ansible_version: 2.0
  platforms:
    - name: EL
      versions:
        - all
    - name: Fedora
      versions:
        - all
    - name: Debian
      versions:
        - all
    - name: Ubuntu
      versions:
        - all
